drop table if exists zawartosc;
drop table if exists style;
drop table if exists piwo;
drop table if exists sklepy;

CREATE TABLE sklepy (
	idSklepu 		    integer primary key,
	ulicaNrLokalu 	varchar(100) NOT NULL,
	przedsiebiorca 	varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE piwo (
  nazwaPiwa			    varchar(30) primary key,
	nazwaStylu	      varchar(30) not null,
	zawartoscAlkoholu numeric (7,2)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE zawartosc (
	idSklepu		integer not null references sklepy,
  nazwaPiwa		varchar(30) not null references piwo,
	primary key (idSklepu, nazwaPiwa)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


INSERT INTO `sklepy` (`idSklepu`, `ulicaNrLokalu`, `przedsiebiorca`) VALUES
(0, 'Craftownia - Krakowski Wielokran', 'Sw. Wawrzynca 22'),
(1, 'Multi Qlti Tap Bar', 'Szewska 21'),
(2, 'WeŸ¿e Krafta', 'Dolnych Mlynow 10/3'),
(3, 'Omerta', 'Kupa 3'),
(4, 'Pod Wiaduktem', 'Nad Struga 9'),
(5, 'Nowy Kraftowy', 'Plac Nowy 8'),
(6, 'Sklep Maria', 'Kobierzynska 61'),
(7, 'Viva la PINTA', 'ul. Florianska 13'),
(8, 'Miejscówka - Craft Beer Pub', 'Józefiñska 4/2'),
(9, 'Strefa Piwa (Beer Zone)', 'ul. Krowoderska 37'),
(10, 'Strefa Piwa Pub (Beer Zone)', 'Józefa 6'),
(11, 'Strefa Piwa Beliny (Beer Zone)', 'al. Beliny Pra¿mowskiego 49a'),
(12, 'Regionalne Alkohole', 'ul. Miodowa 28a'),
(13, 'Sk³ad piwa i alkoholi', 'ul. Czarnowiejska 91B'),
(14, 'House of Beer', 'ul. sw Tomasza 35'),
(15, 'Beer Concept', '£u¿ycka 25'),
(16, 'Rewia Piwa', 'al. 29 Listopada 42c'),
(17, 'Huta Piwa', 'os. Szkolne 35'),
(18, 'Œwiat Piwa (World of Beer)', 'Karmelicka 51'),
(19, 'Kufle i Widelce', 'Czysta 3/2'),
(20, 'BroPub by Brokreacja', 'Stradomska 11'),
(21, 'Delikatesowo', 'ul. Brodziñskiego 1'),
(22, 'Browar Dwie Wie¿e', 'Pu³kownika Stanis³awa D¹bka 8'),
(23, 'Domówka Cafe', 'ul. Miodowa 28a'),
(24, 'Artefakt Café', 'Dajwór 3'),
(25, 'Baza Pub', 'Florianska 15'),
(26, 'T.E.A. Time', 'Dietla 1'),
(27, 'Ursa Maior Concept Store & Pub', 'plac Wolnica 10'),
(28, 'Bimberek i Piwko', 'Przemiarki 23'),
(29, 'Space Craft Pub', 'ulica Bracka 3-5/7'),
(30, 'SHAKE Maroza - Ruczaj', 'Jana Szwai 16/LU1'),
(31, 'Fog House Pub & Grill', 'Koletek 11'),
(32, 'Czarny Kot Kraków', 'Starowiœlna 42'),
(33, 'BeerGallery - LUXURY', 'Tomasza 30'),
(34, 'KORPO', 'Bora Komorwskiego 9'),
(35, 'Hala G³ówna', 'Dolnych M³ynów 10'),
(36, 'Piwa Regionalne Kraków Wybickiego 8/1', 'Wybickiego 8/1'),
(37, 'Browar Lubicz Restauracya Browarna', 'ul. Lubicz 17J'),
(38, 'Via Caffe', 'Pl. Wolnica 9'),
(39, 'Sklep Piwny', 'Zieliñska'),
(40, 'Irish Pub Pod Papugami', 'ul. Œw. Jana 18'),
(41, 'Poli', 'Dietla 97'),
(42, 'BeerGallery - Dominikañska', 'ul. Dominikañska 3'),
(43, 'Beer House Pub & Restaurant', 'Florianska 43'),
(44, 'Non Iron', 'Sw. Marka 27'),
(45, 'Fortuna & Friends Krakow', 'Ul. Szpitalna 5'),
(46, 'Pub Zaginiony Œwiat', 'Batorego 1'),
(47, 'Plac Nowy 1', 'Plac Nowy 1'),
(48, 'Mostowa ArtCafe', 'ul. Mostowa 8'),
(49, 'Lewiatan Kunickiego Kraków', 'ul. Kunickiego 5'),
(50, 'Szynk', 'Podbrzezie 2'),
(51, 'Auchan Bonarka', 'Kamienskiego 11'),
(52, 'Krako Slow Wines', 'Lipowa 6F'),
(53, 'Miód i Wino', 'S³awkowska 32'),
(54, 'Bull Pub', 'Miko³ajska 2'),
(55, 'Bistro Cafe Bar Trójk¹t', 'ul. Józefa 30'),
(56, 'Carrefour Kraków Galeria Krakowska', 'Pawia 5 CH Galeria Krakowska'),
(57, 'BeerGallery - Kazimierz', 'Warszauera 10'),
(58, 'C.K. Browar', 'Podwale 6-7'),
(59, 'Stajnia', 'Izaaka 7/1'),
(60, 'Karczma Zadyma sklep firmowy', 'Szpitalna 36'),
(61, 'Bierhalle Kraków', 'Ma³y Rynek 7'),
(62, 'Tesco Kapelanka', 'ul. Kapelanka 54'),
(63, 'Bar No7', 'Rynek G³ówny'),
(64, 'U Jo¿ina', 'Œw. Tomasza 7'),
(65, 'Alma Kraków Galeria Kazimierz', 'Podgórska 34'),
(66, 'Stara Zajezdnia', 'Œwiêtego Wawrzyñca 12'),
(67, 'Alchemia', 'Estery 5'),
(68, 'English Football Club', 'ul. Mikolajska 5'),
(69, 'Kaufland', 'ul. Bratys³awska 4'),
(70, 'The Irish Mbassy', 'ul. Stolarska 3'),
(71, 'Sarmacja', 'ul. Œw. Tomasza 8'),
(72, 'Delikatesy Kocyk Miodowa', 'Miodowa 13'),
(73, 'Ekwi Alkohole', 'al. Pokoju 33'),
(74, 'Football Heaven', 'Œwiêtego Filipa 7 Street'),
(75, 'Cafe Czekolada', 'Bracka 4'),
(76, 'Coolturka Pub', 'Estery 1'),
(77, 'Alkohole Kalwaryjska 24', 'ul. Kalwaryjska 24'),
(78, 'Alma Krakow Pilotow', 'ul. Pilotów 6'),
(79, 'Alpo Delikatesy (Kraków - Kazimierza Wielkiego)', 'Kazimierza Wielkiego 1'),
(80, 'BAR BA£TYK', 'Brzozowa 8'),
(81, 'Biedronka Kraków Po³omskiego', 'Po³omskiego 14');

INSERT INTO `piwo` (`nazwaPiwa`, `nazwaStylu`, `zawartoscAlkoholu`) VALUES
('3 Fonteinen Hommage', 'Lambic - Fruited', '4.50'),
('8 Wired / Pinta Baltyk-Tasman ', 'Porter - Baltic', '9.00'),
('8 Wired Flat White Coffee Milk', 'Stout - Sweet', '5.50'),
('8 Wired HopWired IPA', 'IPA', '7.30'),
('8 Wired Once Upon a Time in Bl', 'Lambic - Fruited', '8.50'),
('8 Wired The Big Smoke', 'Smoked', '6.20'),
('Alaskan Smoked Porter', 'Smoked', '6.50'),
('AleBrowar / BrauKunstKeller He', 'Berliner Weisse', '3.80'),
('AleBrowar / First Chop Im not', 'IPA', '5.00'),
('AleBrowar Black Hope', 'IPA - Black / Dark', '6.20'),
('AleBrowar Brown Foot', 'Brown Ale', '6.20'),
('AleBrowar Hop Sasa', 'IPA', '5.00'),
('AleBrowar New England DDH DIPA', 'IPA - Imperial / Double', '8.80'),
('AleBrowar New Wave Gose z Jago', 'Grodziskie/Gose/Lichtenhainer', '4.70'),
('AleBrowar Saint No More', 'Saison', '6.00'),
('AleBrowar Single Hop IPA Mosai', 'IPA', '6.20'),
('AleBrowar Smoky Joe Fan Editio', 'Stout - Foreign / Extra', '6.20'),
('AleBrowar What a Shot', 'IPA', '5.00'),
('AleSmith / Pizza Port Logical ', 'IPA - Imperial / Double', '10.00'),
('AleSmith Double IPA', 'IPA - Imperial / Double', '8.50'),
('AleSmith Nut Brown English-Sty', 'Brown Ale', '5.00'),
('AleSmith Old Numbskull', 'Barley Wine / Wheat Wine', '11.00'),
('AleSmith San Diego Pale Ale .3', 'Pale Ale - American', '6.00'),
('AleSmith Speedway Stout - Hawa', 'Stout - Imperial', '12.00'),
('Amager / Against The Grain Min', 'IPA - Imperial / Double', '8.00'),
('Amager / Edge Brewing Project ', 'IPA', '6.00'),
('Amager / Evil Twin The Real Hr', 'Stout - Imperial', '10.40'),
('Amager Billie the Butcher', 'IPA - Hazy / New England', '7.00'),
('Amager Bonny Beer', 'IPA', '6.50'),
('Amager The Sinner Series Glutt', 'IPA - Imperial / Double', '9.40'),
('Amarcord / PINTA Polish-Italia', 'Fruit Beer', '6.50'),
('Amber Kozlak', 'Bock - Dunkler / Urbock', '6.50'),
('Amber Po Godzinach Marcowe', 'Oktoberfest / Märzen', '0.00'),
('American Browar Polska IPA', 'IPA', '0.00'),
('Anarchia Anarchy Pale Ale', 'Pale Ale - American', '5.30'),
('Anarchia White Vampire', 'Weissbier - Hefeweizen', '4.80'),
('Anchorage Anadromous Belgian B', 'Sour / Wild Ale', '8.50'),
('Anchorage Bitter Monk Belgian ', 'IPA - Imperial / Double', '9.00'),
('Anchorage Galaxy White IPA', 'IPA', '7.00'),
('Anchorage The Tide and Its Tak', 'Abbey Tripel', '9.00'),
('Anderson Valley Briney Melon G', 'Grodziskie/Gose/Lichtenhainer', '4.20'),
('Anderson Valley Framboise Rose', 'Grodziskie/Gose/Lichtenhainer', '4.20'),
('Anderson Valley G&T; Gose', 'Grodziskie/Gose/Lichtenhainer', '4.20'),
('Anderson Valley Hop Hyzer', 'Pale Ale - American', '4.90'),
('Antybrowar Antygrawitacja', 'Brown Ale', '4.30'),
('Antybrowar Antykoncepcja', 'Pale Ale - American', '5.30'),
('Antybrowar Antyoksydant', 'Belgian Ale', '7.50'),
('Antybrowar Proboszcz', 'Stout - Dry', '5.00'),
('Arbor Boomtown Brown', 'Brown Ale', '5.30'),
('Artezan Ba³wan', 'Pale Ale - American', '4.50'),
('Artezan Coffee Kamaz Bourbon B', 'Stout', '7.00'),
('Artezan Coffee Wo³ga', 'Stout', '5.50'),
('Artezan Dodo', 'IPA - Hazy / New England', '6.00'),
('Artezan El Líquido Dorado', 'IPA - Session', '4.80'),
('Artezan Format C:', 'IPA - Session', '4.50'),
('Artezan Pacific Pale Ale', 'Pale Ale - American', '5.00'),
('Artezan Panie Co Pan?', 'IPA', '6.00'),
('Artezan Preparat', 'Barley Wine / Wheat Wine', '9.00'),
('Artezan Samiec Alfa (Barrel Ag', 'Stout - Imperial', '13.00'),
('Artezan Te Czasy Siê Skoñczy³y', 'IPA', '6.50'),
('Artezan Too Young To Be Herod ', 'Stout - Imperial', '10.00'),
('Artezan VI', 'IPA', '6.00'),
('Artezan Wiewiór', 'Brown Ale', '8.00'),
('Artezan Zgrana Karta', 'IPA', '6.50'),
('Artezan ¯ukiem Do Rzymu', 'Sour / Wild Ale', '4.60'),
('Aslin Gose (Blackberry & Raspb', 'Grodziskie/Gose/Lichtenhainer', '4.50'),
('Aufsesser Zwickl', 'Zwickel / Keller / Landbier', '4.80'),
('Bakalár Rezaná Desitka', 'Polotmavý', '4.20'),
('Bakaláø Svìtlé Výèepní 10°', 'Czech Pilsner (Svìtlý)', '4.00'),
('Baladin Lune Riserva Teo Musso', 'Barley Wine / Wheat Wine', '11.50'),
('Baltika 9 Krepkoe (Strong)', 'Imperial Pils/Strong Pale Lage', '8.00'),
('Barbakan Jasne', 'Pale Lager', '5.90'),
('Bax Bier Ketter', 'Smoked', '8.50'),
('Bax Bier Koud Vuur', 'Smoked', '6.20'),
('Bazyliszek Sen o Warszawie', 'Stout - Sweet', '6.60'),
('Bear Republic Café Racer 15', 'IPA - Imperial / Double', '9.75'),
('Bear Republic Racer 5 IPA', 'IPA', '7.50'),
('Bednary Ale Ciacho! Special Ed', 'Spice / Herb / Vegetable', '5.00'),
('Bednary Orzeszek', 'Brown Ale', '6.30'),
('BeerLab Piaseczyñskie Polskie ', 'Specialty Grain', '5.10'),
('Belhaven Scottish Ale (US Vers', 'Scottish Ale', '5.20'),
('Bernard Svìtlý Ležák 12° / Pre', 'Czech Pilsner (Svìtlý)', '4.90'),
('Bia³y Kot', 'Premium Lager', '5.50'),
('Bierhalle Piwo Ciemne (Dunkel)', 'Dunkel / Tmavy', '4.90'),
('Birbant / Szpunt Telepathic', 'IPA', '5.00'),
('Birbant Atomic Lucy', 'IPA - Imperial / Double', '7.80'),
('Birbant Fruity DDH Imperial Ci', 'IPA - Imperial / Double', '7.90'),
('Birbant Hopsbant Peach Milksha', 'IPA - Hazy / New England', '4.20'),
('Birbant Jamarillo', 'California Common', '5.60'),
('Birbant Porter Ba³tycki Klasyc', 'Porter - Baltic', '10.20'),
('Birra Antoniana Scudata', 'Pale Lager', '5.20'),
('Birra Antoniana Stile Vienna', 'Amber Lager / Vienna', '5.40'),
('Blackberry Farm Barrel Series ', 'Saison', '7.50'),
('Boon Oude Kriek', 'Lambic - Fruited', '6.50'),
('Boundary Gift', 'Stout - Imperial', '8.70'),
('Brauerei Simon Weißbier', 'Weissbier - Hefeweizen', '5.40'),
('Bøeclav Beran 10°', 'Czech Pilsner (Svìtlý)', '4.10'),
('BrewDog Abstrakt AB:24', 'Porter - Baltic', '12.00'),
('BrewDog Christmas Paradox 2012', 'Stout - Imperial', '15.00'),
('BrewDog Jack Hammer', 'IPA', '7.20'),
('BrewDog Nanny State (0.5%)', 'Low Alcohol', '0.50'),
('BrewDog Riptide', 'Stout - Imperial', '8.00'),
('BrewDog vs. Amundsen Mallow Ma', 'Stout - Imperial', '12.00'),
('Brewski / Cycle 50 States of F', 'Berliner Weisse', '3.90'),
('Brewski Barbarian IPA', 'IPA', '6.00'),
('Brewski Red Robot DIPA', 'IPA - Imperial / Double', '7.50'),
('Brewski Three Fourteen IPA', 'IPA', '5.90'),
('Brodacz Marty', 'IPA', '5.00'),
('Brokreacja / Dukla Nafciarz Du', 'Smoked', '6.30'),
('Brokreacja Battle Master 2017', 'Scotch Ale / Wee Heavy', '10.00'),
('Brokreacja Big Boy Apricot', 'IPA', '5.50'),
('Brokreacja Big Boy Cherry', 'IPA', '5.50'),
('Brokreacja Big Boy Lime', 'IPA', '5.50'),
('Brokreacja Big Boy Passion Fru', 'IPA', '5.50'),
('Brokreacja Big Boy Peach', 'IPA', '5.30'),
('Brokreacja Big Boy Strawberry', 'IPA', '5.50'),
('Brokreacja Buried Alive', 'Smoked', '9.50'),
('Brokreacja Buried Alive Laphro', 'Smoked', '9.50'),
('Brokreacja Certain Death', 'Smoked', '9.50'),
('Brokreacja Deep Dark Sea', 'Porter - Baltic', '10.10'),
('Brokreacja Deep Dark Sea Bourb', 'Porter - Baltic', '10.10'),
('Brokreacja Deep Dark Sea Kirsc', 'Porter - Baltic', '10.10'),
('Brokreacja Devil Ink', 'IPA - Session', '5.00'),
('Brokreacja Espressoning', 'Stout - Sweet', '4.40'),
('Brokreacja Imperialny Nafciarz', 'Smoked', '10.00'),
('Brokreacja Potion #1', 'Stout - Imperial', '12.30'),
('Brokreacja Potion #2', 'Brown Ale', '11.00'),
('Brokreacja Potion #3', 'American Strong Ale ', '10.80'),
('Brokreacja Sweet Temptation', 'Barley Wine / Wheat Wine', '10.00'),
('Brokreacja The Barber', 'IPA', '5.80'),
('Brokreacja The Blogger 2016 Re', 'English Strong Ale', '8.10'),
('Brokreacja The Blogger 2017', 'English Strong Ale', '10.20'),
('Brokreacja The Blogger 2018', 'Czech Pilsner (Svìtlý)', '4.00'),
('Brokreacja The Butcher', 'IPA', '7.00'),
('Brokreacja The Cop', 'Pilsener', '4.70'),
('Brokreacja The Dealer', 'Pale Ale - American', '4.70'),
('Brokreacja The Fighter', 'IPA - Imperial / Double', '8.90'),
('Brokreacja The Gravedigger Bou', 'Stout - Imperial', '10.30'),
('Brokreacja The Gravedigger Lap', 'Stout - Imperial', '10.30'),
('Brokreacja The Miner', 'IPA - Black / Dark', '6.70'),
('Brokreacja Title Role - Salty ', 'Grodziskie/Gose/Lichtenhainer', '4.50'),
('Brokreacja Trip-Hop Galaxy Mos', 'IPA - Hazy / New England', '6.60'),
('Brokreacja Wine Cake Polish Wi', 'Barley Wine / Wheat Wine', '11.00'),
('Brooklyn Sorachi Ace', 'Saison', '7.60'),
('Brovaria Porter Ba³tycki Barre', 'Porter - Baltic', '9.00'),
('Brovca Atlantyk', 'Pale Ale - American', '5.80'),
('Browanza Bear with a beer', 'IPA', '7.20'),
('Browanza Second Fiddle', 'Wheat Ale', '7.00'),
('Browar Grodzisk Grodziska APA', 'Pale Ale - American', '5.20'),
('Browar Grodzisk Grodziska Whit', 'IPA', '6.00'),
('Browar Jana American Stout', 'Stout - Foreign / Extra', '6.00'),
('Browar Jana Gruby Joe', 'Stout', '6.00'),
('Browar Jana Jasne Pe³ne', 'Golden Ale / Blond Ale', '5.20'),
('Browar Jana Oktavio 500 Days o', 'Abbey Quadrupel / Abt', '9.20'),
('Browar Jana Owocowy Hefe-Weize', 'Weissbier - Hefeweizen', '5.60'),
('Browar Jana Pils', 'Pilsener', '5.60'),
('Browar Jana Porter Ba³tycki', 'Porter - Baltic', '8.80'),
('Browar Jana ¯ytnie IPA', 'IPA', '6.40'),
('Browar na Jurze Ale Meksyk', 'Low Alcohol', '2.00'),
('Browar na Jurze La Bella Sicil', 'IPA', '8.00'),
('Browar na Jurze Ró¿owa Pantera', 'IPA', '5.00'),
('Browar Stu Mostów ART12 / Haan', 'Fruit Beer', '3.50'),
('Browar Stu Mostów ART22 / Nort', 'India Style Lager', '7.90'),
('Browars HOPIN', 'IPA', '5.60'),
('Browars Piwo Limanowskie Ale', 'Traditional Ale', '4.70'),
('Browars Risnieft', 'Stout - Imperial', '8.00'),
('Budweiser Budvar Bud B:Strong ', 'Imperial Pils/Strong Pale Lage', '7.50'),
('Bytów Vermont IPA', 'IPA', '5.90'),
('Bytów Wojtas Na Gazie - Pils', 'Pilsener', '4.30'),
('C.K Browar Imbirowe (Ingwer)', 'Spice / Herb / Vegetable', '0.00'),
('C.K. Browar AIPA', 'IPA', '6.00'),
('C.K. Browar Dunkel', 'Bock - Dunkler / Urbock', '7.00'),
('C.K. Browar Jasne (Pils)', 'Pilsener', '5.50'),
('C.K. Browar Miodowe', 'Dortmunder', '5.00'),
('C.K. Browar Radler', 'Radler / Shandy', '3.40'),
('C.K. Browar Vermont IPA', 'IPA - Hazy / New England', '5.00'),
('C.K. Browar Weizen', 'Weissbier - Hefeweizen', '0.00'),
('Caldera Mogli - Bourbon Barrel', 'Porter - Imperial / Double', '8.50'),
('Caldera Mosaic IPA', 'IPA', '6.50'),
('Camba Bavaria Black Pearl (Imp', 'Stout - Imperial', '9.80'),
('Carlow OHaras 51st State IPA', 'IPA', '6.00'),
('Carlow OHaras Irish Stout', 'Stout - Dry', '4.30'),
('Carlow OHaras Leann Folláin', 'Stout - Dry', '6.00'),
('Cascade Manhattan NW', 'Sour / Wild Ale', '11.32'),
('Central Waters Brewers Reserv', 'Abbey Quadrupel / Abt', '11.90'),
('Chimay Grande Réserve Vieillie', 'Belgian Strong Ale', '10.50'),
('Chodovar Èerná Desítka 10°', 'Dunkel / Tmavy', '4.20'),
('Cigar City Cafe Con Leche Stou', 'Stout - Sweet', '6.00'),
('Cigar City Marshal Zhukovs Im', 'Stout - Imperial', '11.80'),
('Clock No Idols! 13° India Pale', 'India Style Lager', '5.50'),
('Cloudwater A•W18 Brewed All Se', 'IPA - Imperial / Double', '8.50'),
('Cloudwater A•W18 DIPA V2', 'IPA - Imperial / Double', '8.50'),
('Cloudwater A•W18 Small Pale Br', 'IPA - Session', '2.90'),
('Cloudwater MCR DIPA Citra BBC', 'IPA - Imperial / Double', '8.50'),
('Collective Arts Collective Pro', 'Porter - Imperial / Double', '8.60'),
('Collective Arts Ransack the Un', 'IPA', '6.80'),
('Crooked Stave St. Bretta (Autu', 'Sour / Wild Ale', '5.50'),
('Cydr Chyliczki Lodowy 2017', 'Ice Cider / Ice Perry', '11.80'),
('Cydr Chyliczki Sweet Oak ', 'Cider', '13.50'),
('Czarna Owca exlibRIS', 'Stout - Imperial', '10.00'),
('Czarna Owca exlibRIS Bourbon B', 'Stout - Imperial', '10.00'),
('Czarna Owca Porter Noster Bour', 'Porter - Baltic', '9.00'),
('Czarna Owca Porter Noster Cogn', 'Porter - Baltic', '9.00'),
('Cztery Œciany Gniazdo', 'Stout - Sweet', '4.60'),
('Cztery Sciany Goœæ', 'Wheat Ale', '4.70'),
('Cztery Œciany Jama', 'IPA - Black / Dark', '6.00'),
('Cztery Œciany Kamper', 'IPA', '6.40'),
('Cztery Œciany Ranzco', 'Pale Ale - American', '4.50'),
('Cztery Sciany Session Hacjenda', 'Saison', '5.40'),
('De Dolle Boskeun', 'Belgian Strong Ale', '10.00'),
('De Dolle Dulle Teve 10o (Mad B', 'Abbey Tripel', '10.00'),
('De Dolle Special Extra Export ', 'Stout - Foreign / Extra', '9.00'),
('De Helder -  Semi Dark', 'Polotmavý', '4.60'),
('De Moersleutel Octane Overlord', 'Stout - Imperial', '11.00'),
('De Moersleutel Smeerolie Cocon', 'Stout - Imperial', '10.00'),
('De Molen #3000 (White Wine BA)', 'Barley Wine / Wheat Wine', '14.60'),
('De Molen / Hair of the Dog Bin', 'Barley Wine / Wheat Wine', '14.40'),
('De Molen / Tempest Sun & Moon', 'Stout - Imperial', '10.00'),
('De Molen Amarillo', 'IPA - Imperial / Double', '9.30'),
('De Molen Bloed Zweet & Tranen ', 'Smoked', '8.20'),
('De Molen Hel & Verdoemenis Bow', 'Stout - Imperial', '11.80'),
('De Molen Hel & Verdoemenis Bru', 'Stout - Imperial', '12.00'),
('De Molen Hemel & Aarde (Heaven', 'Stout - Imperial', '10.00'),
('De Molen Hutje & Mutje Woodfor', 'English Strong Ale', '13.00'),
('De Molen Juicy Loesie', 'Barley Wine / Wheat Wine', '12.70'),
('De Molen Tsarina Esra Imperial', 'Porter - Imperial / Double', '11.00'),
('De Molen Tsarina Esra Woodford', 'Porter - Imperial / Double', '11.90'),
('De Molen Weer & Wind (2016)', 'Barley Wine / Wheat Wine', '12.40'),
('De Ranke Guldenberg', 'Belgian Strong Ale', '8.00'),
('De Ranke Hop Harvest 2017', 'Belgian Ale', '5.50'),
('De Ranke XX Bitter ', 'Belgian Ale', '6.00'),
('Deer Bear Blend Battle Vol. 3 ', 'IPA - Imperial / Double', '7.20'),
('Deer Bear Candy Shop - Nut Cak', 'Stout - Imperial', '9.00'),
('Deer Bear Candy Shop Marshmall', 'Stout - Imperial', '10.00'),
('Deer Bear Chocolate Factory', 'Stout - Sweet', '5.90'),
('Deer Bear Coffee Break', 'Stout', '6.50'),
('Deer Bear Czyste Z³oto', 'Pilsener', '5.00'),
('Deer Bear Freak Fight', 'IPA - Imperial / Double', '8.00'),
('Deer Bear Jasumi', 'Pale Ale - American', '5.10'),
('Deer Bear KAME HAME Orange Man', 'IPA', '5.00'),
('Deer Bear La Di Da Di', 'IPA - Hazy / New England', '5.00'),
('Deer Bear Lets Cook - Sour AP', 'Sour / Wild Ale', '5.00'),
('Deer Bear Lets Cook Mango Gos', 'Grodziskie/Gose/Lichtenhainer', '4.60'),
('Deer Bear Sofa King', 'IPA', '5.90'),
('Dieu du Ciel! / The Alchemist ', 'IPA', '6.90'),
('Dieu du Ciel! Aphrodisiaque', 'Stout', '6.50'),
('Dieu du Ciel! Derniere Volonté', 'Sour / Wild Ale', '7.00'),
('Dieu du Ciel! Immoralité', 'IPA - Imperial / Double', '9.20'),
('Dieu du Ciel! Péché Mortel (Bo', 'Stout - Imperial', '9.50'),
('Dieu du Ciel! Péché Mortel Isl', 'Stout - Imperial', '9.50'),
('Dieu du Ciel! Rigor Mortis Abt', 'Abbey Quadrupel / Abt', '10.50'),
('Doctor Brew Barley Wine', 'Barley Wine / Wheat Wine', '10.50'),
('Doctor Brew Double Mosaic Oran', 'Sour / Wild Ale', '4.80'),
('Doctor Brew Experimental Vermo', 'IPA', '5.80'),
('Doctor Brew Pszeniczne', 'Weissbier - Hefeweizen', '4.00'),
('Doctor Brew San Escobeer Brzos', 'Low Alcohol', '1.50'),
('Doctor Brew San Escobeer Mango', 'Pale Ale - American', '3.00'),
('Doctor Brew San Escobeer Marak', 'Pale Ale - American', '3.00'),
('Doctor Brew San Escobeer Pinac', 'Pale Ale - American', '3.00'),
('Dolina BoBRU Trickster', 'IPA', '5.60'),
('Drakes Drakonic Imperial Stout', 'Stout - Imperial', '8.75'),
('Dubuisson Cuvée des Trolls', 'Belgian Ale', '7.00'),
('Dugges Black Currant', 'Sour / Wild Ale', '4.50'),
('Dugges Orange Haze', 'IPA', '6.40'),
('DUM & Pinta Ba³tyk-Atlantico', 'Porter - Baltic', '9.00'),
('Dunham Petit Bouddha', 'Saison', '6.10'),
('Durham Diabolus', 'Stout - Imperial', '10.00'),
('Dvùr Chýnì Klasický Ležák 11°', 'Czech Pilsner (Svìtlý)', '4.00'),
('Dwie Wie¿e Cytrusowy Ale', 'Pale Ale - American', '5.50'),
('Dwie Wie¿e Flanders Red Ale Re', 'Sour Red / Brown', '6.00'),
('Dwie Wie¿e Gruszka Morela Sour', 'Sour / Wild Ale', '5.50'),
('Dwie Wie¿e Orki z Majorki', 'Sour / Wild Ale', '5.00'),
('Dwie Wie¿e RIS', 'Stout - Imperial', '9.00'),
('Dwie Wie¿e Saison Red Wine Bar', 'Saison', '6.30'),
('Dwóch Braci Filemoon', 'Stout', '4.70'),
('Dwóch Braci Manolo', 'IPA - Hazy / New England', '5.00'),
('Dwóch Braci £owca', 'IPA', '6.00'),
('Dzika Pszczo³a - Mango', 'Mead', '9.00'),
('Dziki Wschód Kwaœny Olek', 'Berliner Weisse', '3.00'),
('Dziki Wschód Kwaœny Olek Czarn', 'Berliner Weisse', '3.00'),
('EB Premium', 'Pale Lager', '5.20'),
('Epic Big Bad Baptist ', 'Stout - Imperial', '12.70'),
('Epic Big Bad Baptista', 'Stout - Imperial', '11.70'),
('Epic Son of a Baptist - Corvus', 'Stout - Imperial', '8.00'),
('Evil Twin / Omnipollo Half & H', 'IPA', '7.00'),
('Evil Twin / Omnipollo Pink Lem', 'IPA', '7.00'),
('Evil Twin / Prairie Bible Belt', 'Stout - Imperial', '13.00'),
('Evil Twin Bozo Beer', 'Stout - Imperial', '17.20'),
('Evil Twin Even More Coco Jesus', 'Stout - Imperial', '12.00'),
('Evil Twin Every Day Once A Day', 'IPA - Imperial / Double', '9.00'),
('Evil Twin Harlans Even More J', 'Stout - Imperial', '12.00'),
('Evil Twin Imperial Biscotti Br', 'Porter - Imperial / Double', '11.50'),
('Evil Twin Imperial Biscotti Ch', 'Stout - Imperial', '11.50'),
('Evil Twin Imperial Doughnut Br', 'Porter - Imperial / Double', '11.50'),
('Evil Twin Lost Souls', 'IPA - Hazy / New England', '7.00'),
('Faktoria Alcatraz', 'Barley Wine / Wheat Wine', '9.20'),
('Faktoria Rio Bravo', 'Pale Ale - American', '4.80'),
('Faktoria Rio Bravo z ja³owcem', 'Pale Ale - American', '4.80'),
('Fantôme de Noël', 'Saison', '10.00'),
('Fierce Imperial Cafe Racer', 'Porter - Imperial / Double', '8.00'),
('Fischer Tradition', 'Pale Lager', '6.00'),
('Flying Dog Double Dog Double I', 'IPA - Imperial / Double', '11.50'),
('Flying Dog The Truth Imperial ', 'IPA - Imperial / Double', '8.70'),
('Flying Monkeys Netherworld Cas', 'IPA - Black / Dark', '6.00'),
('Fortuna Komes Barley Wine', 'Barley Wine / Wheat Wine', '12.00'),
('Fortuna Komes Poczwórny Burszt', 'Abbey Quadrupel / Abt', '10.00'),
('Fortuna Komes Porter Baltycki ', 'Porter - Baltic', '9.00'),
('Fortuna Komes Russian Imperial', 'Stout - Imperial', '12.00'),
('Founders Breakfast Stout', 'Stout - Imperial', '8.30'),
('Founders Curmudgeons Better H', 'Old Ale', '12.70'),
('Founders DankWood', 'American Strong Ale ', '12.20'),
('Fourpure / Sunset Brew Nightfa', 'Stout - Imperial', '9.00'),
('Fourpure Deucebox', 'IPA - Imperial / Double', '8.30'),
('Full Sail Session Dark Lager', 'Dunkel / Tmavy', '5.40'),
('Funky Fluid Classic 5 AIPA', 'IPA', '7.20'),
('Funky Fluid Full Time', 'IPA - Hazy / New England', '7.70'),
('Funky Fluid Funny NEIPA', 'IPA - Hazy / New England', '5.90'),
('Funky Fluid Gonna Be Late', 'IPA', '6.40'),
('Funky Fluid Pils Please', 'Czech Pilsner (Svìtlý)', '4.60'),
('Funky Fluid Smooth Wheat IPA', 'Wheat Ale', '5.40'),
('Garage / Barrier That Chihuahu', 'IPA - Imperial / Double', '8.00'),
('Garage / Civil Society / 3 Sta', 'IPA - Session', '4.80'),
('Garage Triangles', 'IPA', '5.00'),
('Gentleman Beskidzki Traper', 'Amber Lager / Vienna', '5.20'),
('Gloger Atomowa Babka', 'Belgian Ale', '5.70'),
('Gloger Koks', 'Golden Ale / Blond Ale', '5.30'),
('Gloger Wredna Morga', 'Golden Ale / Blond Ale', '4.50'),
('Gniewosz Na Miodzie Akacjowym', 'Spice / Herb / Vegetable', '5.60'),
('Golem / White Stork O.D.A.A.L.', 'IPA - Session', '5.00'),
('Golem Cynik', 'Stout - Foreign / Extra', '5.50'),
('Golem Double Dybuk', 'Porter - Imperial / Double', '10.00'),
('Golem Double Dybuk Bourbon Bar', 'Porter - Imperial / Double', '10.00'),
('Golem Double Dybuk Laphroaig B', 'Porter - Imperial / Double', '10.00'),
('Golem Lilith Rum Barrel-Aged', 'Stout - Imperial', '10.00'),
('Golem Mazal Adar Dagim', 'Wheat Ale', '4.20'),
('Golem Milky Moon Rum BA', 'Stout - Imperial', '8.20'),
('Golem Moloch Bourbon BA', 'English Strong Ale', '9.20'),
('Golem Sour Hazy Orange IPA', 'Sour / Wild Ale', '4.70'),
('Golem ???? ???? (Owech Hazy DI', 'IPA - Imperial / Double', '7.20'),
('Golem ???? ???? ???? (Owech Ow', 'IPA - Imperial / Double', '9.50'),
('Good Game Clutchmeister', 'Pilsener', '4.10'),
('Goœciszewo Czarne Krzy¿ackie', 'Schwarzbier', '6.50'),
('Grand Champion 2016 Fruit Whea', 'Fruit Beer', '5.50'),
('Grand Champion Birofilia 2014 ', 'Abbey Dubbel', '8.50'),
('Green Head - Green Party', 'IPA - Hazy / New England', '5.50'),
('Grodzisk / Live Oak Grodziskie', 'Grodziskie/Gose/Lichtenhainer', '7.00'),
('Grodzisk / Sza³piw Vermont IPA', 'IPA', '6.00'),
('Grodzisk Porter Œliwkowy', 'Porter - Baltic', '10.00'),
('Gzub Bombadil', 'Sour / Wild Ale', '4.10'),
('Gzub Easy', 'Low Alcohol', '2.80'),
('Gzub Melt', 'Sour / Wild Ale', '4.10'),
('Gzub White APA', 'Pale Ale - American', '5.10'),
('HaandBryggeriet / Cervisiam / ', 'Stout - Sweet', '10.00'),
('HaandBryggeriet / Jabeerwocky ', 'Porter - Baltic', '10.00'),
('HaandBryggeriet Even S´More Xm', 'Porter - Baltic', '11.10'),
('HaandBryggeriet Odins Tipple', 'Stout - Imperial', '11.00'),
('HaandBryggeriet Xmas IPA', 'IPA - Imperial / Double', '9.00'),
('Harpagan Kl¹twa Masztalerza', 'Sour / Wild Ale', '5.60'),
('Harpagan Korkotrampki Pop³ochu', 'India Style Lager', '4.20'),
('Harpagan Kuracja Szamana', 'Grodziskie/Gose/Lichtenhainer', '3.50'),
('Harpagan Schiza Heretyka', 'Stout - Foreign / Extra', '6.10'),
('Harpagan Wombatopata', 'Pale Ale - American', '5.00'),
('HedgeHog Cherry Milkshake Stou', 'Stout - Sweet', '4.30'),
('Heretic Evil Cousin', 'IPA - Imperial / Double', '8.00'),
('Hopito Jungle Smoothie', 'IPA', '6.10'),
('Hopito Swizzy', 'IPA - Hazy / New England', '6.00'),
('Hopium Bruce Wheatlis', 'Wheat Ale', '5.40'),
('Hopium Dawid Hazylhopp', 'IPA', '5.40'),
('Hopium Freddie Maracuy', 'Fruit Beer', '5.40'),
('Hopium Fruitger Hauer', 'Wheat Ale', '5.80'),
('Hopium Fruitger Young	 ', 'Wheat Ale', '4.50'),
('Hopium Hanss K³oss', 'IPA - Session', '4.40'),
('Hopium Hoppy-Wan Kenhoppy', 'IPA - Imperial / Double', '7.50'),
('Hopium John Limon', 'Wheat Ale', '5.00'),
('Hopium Marian Ryeewski', 'Stout', '5.50'),
('Hopium Mick Lagger', 'Premium Lager', '3.70'),
('Hopium Miroslav Gose', 'Grodziskie/Gose/Lichtenhainer', '5.30'),
('Hopium Penelope Trus', 'Fruit Beer', '5.50'),
('Hopium Vincent Man Gogh', 'Fruit Beer', '5.60'),
('Hopium Violetta Vanillas', 'Stout - Sweet', '5.00'),
('Hoplala Perfekcyjna Pani Domu', 'Oktoberfest / Märzen', '5.30'),
('Hoplala Piêkna M¹dra Zdolna', 'Pale Ale - American', '5.40'),
('Hoppin Frog Extended Barrel A', 'Stout - Imperial', '9.40'),
('Hoppy Lab Earl Grey Pale Ale', 'Pale Ale - American', '0.00'),
('Hoppy Lab Œwidnickie Jasne ', 'Pale Ale - American', '3.30'),
('Hoppy Lab Xmas Pale Ale', 'Spice / Herb / Vegetable', '3.90'),
('Huta Piwa / Stary Kraków Ameri', 'Saison', '5.60'),
('Huta Piwa Handlowe', 'IPA - Imperial / Double', '7.50'),
('Hütt Naturtrüb', 'Zwickel / Keller / Landbier', '4.90'),
('Incognito Black IPA', 'IPA - Black / Dark', '6.00'),
('Incognito New England IPA', 'IPA - Hazy / New England', '6.00'),
('Inne Beczki / AleBrowar Wine N', 'Fruit Beer', '6.20'),
('Jabeerwocky / Profesja Dobosz', 'Wheat Ale', '4.10'),
('Jablonowo 16000 h.b.c. Barley ', 'Barley Wine / Wheat Wine', '10.50'),
('Jablonowo Russian Imperial Sto', 'Stout - Imperial', '10.00'),
('Jab³onowo Jasne Pe³ne', 'Pale Lager', '5.80'),
('Jab³onowo Manufaktura Piwna Po', 'Porter - Baltic', '9.90'),
('Jackie Os / Creature Comforts', 'Barley Wine / Wheat Wine', '11.50'),
('Jackie Os Bourbon Barrel Blac', 'Porter - Imperial / Double', '11.00'),
('Jackie Os Bourbon Barrel Skip', 'Abbey Quadrupel / Abt', '9.40'),
('Jackie Os Wood Ya Honey', 'Barley Wine / Wheat Wine', '12.00'),
('Jagie³³o Na³êczowskie Ciemne', 'Dunkel / Tmavy', '6.00'),
('Jan Olbracht Legenda Króla', 'Stout - Imperial', '11.00'),
('Jan Olbracht Rzemieœlniczy  RI', 'Stout - Imperial', '12.00'),
('Jan Olbracht Rzemieœlniczy Pie', 'Spice / Herb / Vegetable', '5.60'),
('Jan Olbracht Rzemieœlniczy Œmi', 'Weissbier - Hefeweizen', '5.60'),
('Jolly Pumpkin Luciernaga  (The', 'Belgian Ale', '6.50'),
('Jolly Pumpkin Oro de Calabaza', 'Belgian Strong Ale', '8.00'),
('Jopen / Browar Stu Mostów Poli', 'Porter - Baltic', '9.20'),
('Jopen / Frontaal Yankee Punch', 'IPA - Imperial / Double', '7.60'),
('Jopen Kruistocht van Thomas', 'American Strong Ale ', '10.00'),
('Jurajskie Amerykañska Pszenica', 'Wheat Ale', '4.00'),
('Jurajskie Motocyklowe', 'Low Alcohol', '0.50'),
('Jurajskie Œwi¹teczne', 'Spice / Herb / Vegetable', '5.60'),
('Karpat Belgian Wheat IPA 125%', 'IPA', '4.80'),
('Karpat Mustang American ALE 13', 'Pale Ale - American', '4.60'),
('Karpat Stout 13°', 'Stout', '4.50'),
('Karpat Summer California Ale 1', 'Pale Ale - American', '4.50'),
('Karuzela Sady', 'Pale Ale - American', '5.80'),
('Kasteel Rouge', 'Fruit Beer', '8.00'),
('Kazimierz Mango³', 'Pale Ale - American', '4.20'),
('Kazimierz Spichlerz Europy', 'Weissbier - Hefeweizen', '5.30'),
('Kingpin Amadeo', 'IPA - Hazy / New England', '4.30'),
('Kingpin Beatnik', 'IPA', '6.30'),
('Kingpin Imperial Geezer', 'Stout - Imperial', '9.10'),
('Kingpin Intergalactic', 'India Style Lager', '5.00'),
('Kingpin Midlife Maestro', 'IPA - Hazy / New England', '5.70'),
('Kingpin Most Wanted', 'Wheat Ale', '4.90'),
('Kingpin Pixie Dust', 'IPA - Imperial / Double', '9.00'),
('Kingpin Senor Ehuehue', 'IPA - Imperial / Double', '5.70'),
('Kingpin Turbo Geezer', 'Stout - Foreign / Extra', '8.30'),
('Klášter Ležák 11°', 'Czech Pilsner (Svìtlý)', '4.60'),
('Konrad Vratislavický Ležák 11°', 'Czech Pilsner (Svìtlý)', '4.80'),
('Konstancin IPA', 'IPA', '6.20'),
('Kopyra & Widawa Shark', 'IPA - Session', '4.90'),
('Kormoran 1 na 100 Pigwowiec i ', 'Low Alcohol', '1.00'),
('Kormoran BezGlutenNowe #1', 'Specialty Grain', '4.90'),
('Kormoran Chill Beer', 'IPA - Session', '4.80'),
('Kormoran Imperium Prunum', 'Porter - Baltic', '11.00'),
('Kormoran Podroze Kormorana Ame', 'IPA', '6.00'),
('Kormoran Porter Warminski', 'Porter - Baltic', '9.00'),
('Kormoran Porter Warmiñski z Wi', 'Porter - Baltic', '8.50'),
('Kormoran Wisnia w Piwie', 'Fruit Beer', '5.20'),
('Koœcierzyna Red Lager', 'Amber Lager / Vienna', '5.50'),
('Koutský 12° Svìtlý Ležák ', 'Czech Pilsner (Svìtlý)', '5.00'),
('Kraftwerk Midnight Howl', 'Stout - Imperial', '8.50'),
('Královar Lehke Svetlé Pivo', 'Pale Lager', '3.40'),
('Ksiaz ( Ksiazecy Specjal )', 'Pale Lager', '5.00'),
('Ksi¹¿êce Ciemne £agodne', 'Dunkel / Tmavy', '4.10'),
('Ksi¹¿êce IPA', 'IPA', '5.40'),
('Kustosz 100% Chmiel Sybilla', 'Pale Lager', '5.50'),
('La Pirata / Les Trois Mousquet', 'IPA', '6.50'),
('La Pirata Liquid Fear', 'IPA - Imperial / Double', '8.70'),
('La Pirata !Ay Carmela!', 'IPA - Imperial / Double', '9.30'),
('La Trappe Blond', 'Belgian Ale', '6.50'),
('La Trappe Quadrupel', 'Abbey Quadrupel / Abt', '10.00'),
('Langier Beer APA', 'Pale Ale - American', '5.10'),
('Langier Beer Forever White IPA', 'IPA', '6.00'),
('Langier Beer Hazy Crazy', 'IPA', '5.60'),
('Langier Beer Session IPA', 'IPA - Session', '5.00'),
('Laugar Aupa Tovarisch', 'Stout - Imperial', '11.30'),
('Laugar Funky Espresso ', 'Sour / Wild Ale', '4.80'),
('Lervig Barley Wine 2017 BA Bou', 'Barley Wine / Wheat Wine', '12.90'),
('Les Trois Mousquetaires Porter', 'Porter - Baltic', '10.00'),
('Lindemans Apple (Pomme)', 'Lambic - Fruited', '3.50'),
('Lindemans Cassis Lambic', 'Lambic - Fruited', '3.50'),
('Lindemans Faro', 'Lambic - Faro', '4.50'),
('Lindemans Gueuze Cuvée René', 'Lambic - Gueuze', '5.50'),
('Lindemans Kriek ', 'Lambic - Fruited', '3.50'),
('Litovel Pšenièny Ležák', 'Weissbier - Hefeweizen', '4.70'),
('Logsdon The Conversion', 'Sour / Wild Ale', '7.80'),
('Lost Abbey Box Set: Track #10 ', 'Stout - Imperial', '13.50'),
('Lost Abbey Dead Mans Game', 'Belgian Strong Ale', '14.00'),
('Lost Coast Fogcutter Double IP', 'IPA - Imperial / Double', '8.70'),
('Lost Coast Indica India Pale A', 'IPA', '6.50'),
('Lubicz APA', 'Pale Ale - American', '5.60'),
('Lubicz Ciemne', 'Dunkel / Tmavy', '5.10'),
('Lubicz Le¿ak', 'Czech Pilsner (Svìtlý)', '5.60'),
('Lubicz Marcowe', 'Oktoberfest / Märzen', '6.50'),
('Lubicz Mistrzowskie', 'Fruit Beer', '5.50'),
('Lubicz Pszeniczne', 'Weissbier - Hefeweizen', '5.60'),
('Lubicz Zimowe', 'Dunkel / Tmavy', '4.40'),
('Lubuskie o Smaku Aloesu Winogr', 'Spice / Herb / Vegetable', '4.20'),
('Lubuskie Truskawkowe', 'Fruit Beer', '4.20'),
('Lulu coffee stout', 'Stout - Sweet', '4.50'),
('Lulu Mango Hefeweizen', 'Fruit Beer', '4.50'),
('Lulu Peach Gose', 'Grodziskie/Gose/Lichtenhainer', '3.50'),
('Lulu Raspberry APA', 'Pale Ale - American', '4.90'),
('Lvivske Porter', 'Porter - Baltic', '8.00'),
('Magic Rock / Kissmeyer Salty K', 'Grodziskie/Gose/Lichtenhainer', '4.10'),
('Magic Rock Common Grounds', 'Porter', '5.40'),
('Magic Rock High Wire Grapefrui', 'Pale Ale - American', '5.50'),
('Marble Ezekiel', 'IPA', '6.30'),
('Marble Little Wolf', 'IPA', '6.30'),
('Markowy Puszczyk Bia³owieski', 'Stout - Sweet', '4.90'),
('Maryensztadt #1 Projekt 30', 'Porter - Baltic', '10.50'),
('Maryensztadt #2 Projekt 30', 'Barley Wine / Wheat Wine', '15.30'),
('Maryensztadt #3 Projekt 30', 'Scotch Ale / Wee Heavy', '11.63'),
('Maryensztadt Belgijka Na Drugi', 'Abbey Dubbel', '7.50'),
('Maryensztadt Czarnolas ', 'IPA - Black / Dark', '7.60'),
('Maryensztadt Gor¹czka Sezonu', 'IPA - Imperial / Double', '8.40'),
('Maryensztadt Grodzisz', 'Grodziskie/Gose/Lichtenhainer', '3.00'),
('Maryensztadt Gwiazda Pó³nocy', 'Porter - Baltic', '10.10'),
('Maryensztadt Mysterious IPA', 'IPA - Hazy / New England', '6.50'),
('Maryensztadt Polish Hop(e) ', 'Pale Ale - American', '5.50'),
('Maryensztadt Projekt Barrel Ag', 'Barley Wine / Wheat Wine', '9.50'),
('Maryensztadt RaISa Espresso', 'Stout - Imperial', '9.40'),
('Maryensztadt Sourtime Agrest', 'Sour / Wild Ale', '3.50'),
('Maryensztadt Sourtime Blackber', 'Sour / Wild Ale', '6.00'),
('Maryensztadt Sourtime Pineappl', 'Sour / Wild Ale', '4.30'),
('Mc Chouffe', 'Belgian Strong Ale', '8.00'),
('Melvin 2x4', 'IPA - Imperial / Double', '9.90'),
('Melvin Hop Shocker', 'IPA - Imperial / Double', '8.10'),
('Melvin IPA', 'IPA', '7.50'),
('Mikkeller Hva Saa?!', 'Belgian Ale', '6.80'),
('Mikkeller Monks Elixir', 'Abbey Quadrupel / Abt', '10.00'),
('Mikkeller Single Hop Nelson Sa', 'IPA', '6.90'),
('Mikkeller SpontanDoubleRaspber', 'Lambic - Fruited', '8.70'),
('Mikkeller ? / Black', 'Stout - Imperial', '16.10'),
('Minister  ARE YOU NUTS ?', 'Stout - Sweet', '4.70'),
('Minister Are You Nuts?', 'Stout - Sweet', '4.70'),
('Minister Ein Minister', 'Berliner Weisse', '3.20'),
('Minister Ein Minister Malina', 'Berliner Weisse', '3.20'),
('Minister Lucky Ghost', 'IPA', '5.00'),
('Minister Paradajz', 'Pale Ale - American', '5.00'),
('Minne Ardenne Triple au Cognac', 'Abbey Tripel', '8.50'),
('Mi³os³aw Warzy Œmia³o - Borowi', 'Spice / Herb / Vegetable', '5.60'),
('Monsters Joey', 'IPA', '5.00'),
('Monsters Wattie', 'Pale Ale - American', '5.00'),
('Murphys Irish Stout', 'Stout - Dry', '4.00'),
('Naparbier Sandokan ', 'IPA - Imperial / Double', '8.00'),
('Nepomucen / AleBrowar Lazy Bar', 'Grodziskie/Gose/Lichtenhainer', '3.60'),
('Nepomucen / Laugar Hogeita Bos', 'IPA - Imperial / Double', '7.50'),
('Nepomucen / Pinta Viva Œliwa', 'Grodziskie/Gose/Lichtenhainer', '3.90'),
('Nepomucen / Widawa Dark Forest', 'Porter - Baltic', '9.30'),
('Nepomucen Charlotte', 'Fruit Beer', '4.90'),
('Nepomucen Echo', 'Porter - Baltic', '9.50'),
('Nepomucen Forest', 'IPA', '6.00'),
('Nepomucen Nachmielona. Hoptimu', 'Low Alcohol', '0.00'),
('Nepomucen No To Hop', 'IPA', '5.80'),
('Nickel Brook Kentucky Bastard ', 'Stout - Imperial', '14.50'),
('Nickel Brook Malevolent Black ', 'IPA - Black / Dark', '9.50'),
('Niechanowo / Sza³piw Powidz', 'Belgian Strong Ale', '7.60'),
('Nómada Imperial Russian Stout', 'Stout - Imperial', '10.50'),
('Nook Po Korkach', 'Pale Ale - American', '5.00'),
('Nogne O Imperial Stout', 'Stout - Imperial', '9.00'),
('O/O Narangi', 'IPA - Hazy / New England', '6.80'),
('Obolon Bile (White)', 'Witbier', '5.00'),
('Okocim Polskie Ale', 'Amber Ale', '5.00'),
('Okocim Žatecký Svìtlý Ležák', 'Czech Pilsner (Svìtlý)', '5.00'),
('Olimp Elektra', 'Sour / Wild Ale', '5.00'),
('Olimp Hestia', 'IPA', '5.70'),
('Olimp Krios', 'IPA - Imperial / Double', '10.00'),
('Olimp Maja', 'Pale Ale - American', '4.90'),
('Olimp Panakeja', 'IPA', '6.00'),
('Omnipollo / Buxton Original Te', 'Porter - Imperial / Double', '10.00'),
('Omnipollo Hypnopompa Marshmall', 'Stout - Imperial', '11.00'),
('Omnipollo Noa Pecan Mud Cake', 'Stout - Imperial', '11.00'),
('Omnipollo Pleroma', 'Sour / Wild Ale', '6.00'),
('Omnipollo Selassie', 'Stout - Imperial', '11.00'),
('Original Ritterguts Gose', 'Grodziskie/Gose/Lichtenhainer', '4.70'),
('Oskar Blues Old Chub', 'Scotch Ale / Wee Heavy', '8.00'),
('Osowa Góra Bydgoskie Sesyjne', 'Czech Pilsner (Svìtlý)', '5.00'),
('Osowa Góra Singiel', 'Pale Ale - American', '6.20'),
('Oud Beersel Bersalis Tripel Oa', 'Sour / Wild Ale', '10.50'),
('Palatum / Piwoteka Aqua Regia', 'Sour / Wild Ale', '7.00'),
('Palatum Almanicus', 'Pilsener', '5.40'),
('Palatum Amicus Tropicus', 'Sour / Wild Ale', '5.20'),
('Palatum Cold Crush', 'IPA - Black / Dark', '6.80'),
('Palatum Firmus', 'IPA', '6.30'),
('Palatum Illusio', 'Abbey Tripel', '8.20'),
('Palatum Lapsus', 'Grodziskie/Gose/Lichtenhainer', '3.30'),
('Palatum Messis', 'Weissbier - Hefeweizen', '4.20'),
('Palatum N44', 'Saison', '5.30'),
('Palatum Sauria ', 'Sour / Wild Ale', '3.60'),
('Palatum Sentencio', 'IPA - Session', '4.40'),
('Palatum US', 'Bock - Weizenbock', '8.00'),
('Partizan  India Pale Extra Hop', 'IPA', '6.50'),
('Paulaner Salvator', 'Bock - Doppelbock', '7.90'),
('Perun Behemoth Triumviratus', 'IPA', '6.40'),
('Perun Dziedzictwo Lubelski', 'Pale Ale - American', '5.40'),
('Perun Furia Burzy', 'IPA - Imperial / Double', '10.80'),
('Perun Leœne Runo z wiœni¹ i cz', 'Grodziskie/Gose/Lichtenhainer', '5.00'),
('Perun Noc Kupa³y', 'Stout - Foreign / Extra', '6.40'),
('Perun Oblewanie Perperuny Moji', 'Belgian Ale', '4.90'),
('Per³a Chmielowa (Hop Pearl)', 'Pale Lager', '6.00'),
('Per³a Export', 'Premium Lager', '5.60'),
('PINTA / Bakunin Warsaw Express', 'Barley Wine / Wheat Wine', '9.30'),
('Pinta / O\'Hara\'s Lublin to Dub', 'Stout - Foreign / Extra', '7.00'),
('PINTA / To Ol Kwas Ny', 'Sour / Wild Ale', '8.90'),
('PINTA A Ja Pale Ale', 'Pale Ale - American', '4.50'),
('PINTA A Nanasy?', 'Fruit Beer', '7.10'),
('PINTA Angielskie Œniadanie', 'Premium Bitter / ESB', '5.30'),
('PINTA Apetyt Na ¯ycie', 'Specialty Grain', '5.00'),
('PINTA Atak Chmielu', 'IPA', '6.10'),
('PINTA Beauty And The Stout', 'Stout - Foreign / Extra', '6.30'),
('PINTA Do¿ynki', 'Barley Wine / Wheat Wine', '11.50'),
('PINTA Eisbock Grand Prix', 'Bock - Eisbock', '11.30'),
('PINTA FanTassie ', 'Pale Ale - American', '4.70'),
('PINTA Fest Oktober', 'Oktoberfest / Märzen', '5.00'),
('PINTA Final Call', 'IPA - Imperial / Double', '7.00'),
('PINTA Go Deeper', 'IPA', '7.20'),
('PINTA Hazy Morning', 'Pale Ale - American', '4.40'),
('PINTA Im so horny!', 'Bock - Dunkler / Urbock', '6.70'),
('PINTA IIPPAA', 'IPA - Imperial / Double', '8.10'),
('PINTA Imperator Ba³tycki', 'Porter - Baltic', '9.10'),
('PINTA Imperator Ba³tycki Sherr', 'Porter - Baltic', '9.10'),
('PINTA Koniec Œwiata', 'Sahti/Gotlandsdricke/Koduolu', '7.90'),
('PINTA Kwas Epsilon', 'Sour / Wild Ale', '6.00'),
('PINTA Kwas Epsilon Wild & Barr', 'Sour / Wild Ale', '6.90'),
('PINTA Kwas My', 'Fruit Beer', '6.30'),
('PINTA Niedor¿niêty', 'Stout', '3.30'),
('PINTA Parritapa', 'Pale Ale - American', '5.00'),
('PINTA Pierwsza Pomoc', 'Czech Pilsner (Svìtlý)', '4.10'),
('PINTA Psze¿ytowies', 'Specialty Grain', '3.90'),
('PINTA PumpkBlack', 'Porter', '6.00'),
('PINTA Quatro', 'IPA - Imperial / Double', '11.00'),
('PINTA Red Grape Ale', 'Fruit Beer', '8.80'),
('PINTA Risfactor', 'Stout - Imperial', '11.50'),
('PINTA Risfactor Bourbon BA', 'Stout - Imperial', '12.50'),
('PINTA Risfactor Double BA Bour', 'Stout - Imperial', '13.00'),
('PINTA Sangriale', 'Fruit Beer', '4.90'),
('PINTA Shakalaka IPA', 'IPA', '6.40'),
('PINTA Son of a Birch', 'Wheat Ale', '3.00'),
('PINTA TakAHaka', 'IPA - Black / Dark', '7.30'),
('PINTA Weso³ych Œwi¹t 2017', 'Porter - Imperial / Double', '8.40'),
('PINTA Weso³ych Œwi¹t 2018', 'Porter - Imperial / Double', '7.70'),
('Pipeworks Mocha Abduction', 'Stout - Imperial', '10.50'),
('Pivovar Øeporyje Ejlik', 'Pale Ale - American', '4.50'),
('Pivovar Øeporyje Vánoèní svìtl', 'Czech Pilsner (Svìtlý)', '5.00'),
('Pivovsky Fragola', 'IPA - Hazy / New England', '5.60'),
('Piwne Podziemie / Palatum Mr. ', 'IPA - Imperial / Double', '8.60'),
('Piwne Podziemie Double Ego', 'IPA - Imperial / Double', '8.40'),
('Piwne Podziemie Dry Hopped Gra', 'Berliner Weisse', '4.20'),
('Piwne Podziemie Dry Hopped Pin', 'Berliner Weisse', '4.20'),
('Piwne Podziemie Juicilicious', 'IPA - Hazy / New England', '6.70'),
('Piwne Podziemie Sezon Ogórkowy', 'Saison', '5.00'),
('Piwne Podziemie Summer Freakou', 'Wheat Ale', '5.20'),
('Piwne Podziemie Superduper Ses', 'IPA - Session', '3.80'),
('Piwne Podziemie Take It Easy (', 'Golden Ale / Blond Ale', '4.20'),
('Piwne Podziemie Triple Vision', 'IPA - Imperial / Double', '8.50'),
('Piwne Podziemie Weird Era', 'IPA', '6.00'),
('Piwojad Blanka', 'Witbier', '5.00'),
('Piwojad Blanka Pinot Blanc & P', 'Witbier', '5.00'),
('Piwojad Czternastka', 'Czech Pilsner (Svìtlý)', '5.80'),
('Piwojad Muffin', 'Stout - Sweet', '5.10'),
('Piwojad Onyks', 'Stout - Imperial', '8.00'),
('Piwojad RIS 24 Whisky BA', 'Stout - Imperial', '10.10'),
('Piwojad Single Citrus Smoothie', 'IPA', '5.60'),
('Piwojad Single Tropical Smooth', 'IPA - Hazy / New England', '5.40'),
('Piwojad Suska', 'Smoked', '6.40'),
('Piwoteka Angielka', 'Weissbier - Hefeweizen', '5.50'),
('Piwoteka D¿onka Tomka', 'Sour / Wild Ale', '5.10'),
('Piwoteka Eternal Might', 'Stout - Imperial', '10.80'),
('Piwoteka Gabinet Iluzji', 'Stout - Sweet', '3.80'),
('Piwoteka Las £agiewnicki', 'Saison', '7.50'),
('Piwoteka Limonka Hooligans', 'Pale Ale - American', '5.10'),
('Piwoteka Porter Ba³ucki', 'Porter - Baltic', '8.00'),
('Piwoteka Pó³ Czarnej u Roszka', 'Stout - Sweet', '5.50'),
('Piwoteka Zoœka Straszybotka', 'Spice / Herb / Vegetable', '5.50'),
('Piwoteka £ódŸ ku*wa!', 'Barley Wine / Wheat Wine', '12.00'),
('PiwoWarownia / Ghost Twelve Mo', 'IPA', '6.20'),
('PiwoWarownia Blada Marija', 'Sour / Wild Ale', '0.00'),
('PiwoWarownia Chmielum Polelum', 'IPA - Imperial / Double', '8.00'),
('PiwoWarownia Córka M³ynarza', 'Wheat Ale', '4.80'),
('PiwoWarownia Czerwony Kapselek', 'IPA', '5.20'),
('PiwoWarownia Kawko i Mlekosz', 'Stout - Sweet', '4.50'),
('PiwoWarownia Kawko i Mlekosz N', 'Stout - Imperial', '8.00'),
('PiwoWarownia Kosza³ek Hopa³ek', 'Pale Ale - American', '4.60'),
('PiwoWarownia Miêtowa Panienka', 'Low Alcohol', '2.50'),
('PiwoWarownia Oczy Bazyliszka', 'Fruit Beer', '5.20'),
('PiwoWarownia Pe³na Qlturka', 'Stout - Sweet', '5.80'),
('PiwoWarownia Pora Na Chmielesf', 'IPA', '6.00'),
('PiwoWarownia Po¿egnanie Korpor', 'Stout - Imperial', '10.30'),
('PiwoWarownia Rumpelszpunt', 'Abbey Quadrupel / Abt', '10.20'),
('PiwoWarownia xD', 'Stout - Imperial', '8.40'),
('Podgórz / Sza³piw Sza³ Cia³', 'Wheat Ale', '5.00'),
('Podgórz 10W-40', 'IPA', '6.00'),
('Podgórz 652 m n.p.m.', 'Porter - Baltic', '8.00'),
('Podgórz Diabelski M³yn', 'Abbey Quadrupel / Abt', '10.50'),
('Podgórz Galaktyka Piwnix', 'IPA - Black / Dark', '5.60'),
('Podgórz Luzy rajtuzy', 'Amber Ale', '5.00'),
('Podgórz Owca Na Orbicie', 'Witbier', '5.00'),
('Podgórz Owca w Nowej Hucie', 'IPA', '6.00'),
('Podgórz Owca w Tropikach', 'Stout', '6.00'),
('Podgórz Sezon Pomarañczowy', 'Saison', '5.00'),
('Podgórz Siostra Bo¿enka', 'IPA', '6.00'),
('Podgórz Space Sheep', 'Pale Ale - American', '4.50'),
('Podgórz Tatraman', 'Kölsch', '5.00'),
('Pohjala / Jing-A (?A) Cellar S', 'Stout - Imperial', '12.60'),
('Pohjala / To Ol / BRUS Cellar ', 'Stout - Imperial', '12.00'),
('Pohjala Cellar Series - Kolumb', 'Brown Ale', '10.60'),
('Pohjala Cellar Series - Loits', 'Porter - Imperial / Double', '11.50'),
('Pohjala Cherry Bänger', 'Stout - Imperial', '12.50'),
('Pohjala Kirg', 'IPA', '6.00'),
('Pohjala Mets', 'IPA - Black / Dark', '7.00'),
('Pohjala Öö', 'Porter - Baltic', '10.50'),
('Polczyn-Zdroj / Fuhrmann Swojs', 'Dunkel / Tmavy', '4.50'),
('Polièské Otakar Svìtlý Ležák 1', 'Czech Pilsner (Svìtlý)', '4.50'),
('Popihn DIPA Mosaic', 'IPA - Imperial / Double', '8.40'),
('Poutnik Pelhrimov Svìtlý Ležák', 'Czech Pilsner (Svìtlý)', '5.00'),
('Pracownia Piwa / Birrificio It', 'Stout - Sweet', '7.40'),
('Pracownia Piwa / Nemeton Orang', 'Stout - Foreign / Extra', '7.80'),
('Pracownia Piwa / Podgórz Baran', 'Porter - Baltic', '9.50'),
('Pracownia Piwa / To Ol Craft T', 'IPA', '6.80'),
('Pracownia Piwa 900!', 'IPA - Imperial / Double', '7.50'),
('Pracownia Piwa All Inclusive', 'Fruit Beer', '2.30'),
('Pracownia Piwa Captain Baltic ', 'Porter - Baltic', '9.50'),
('Pracownia Piwa Dark Side Of Th', 'Low Alcohol', '2.00'),
('Pracownia Piwa Dwa Smoki', 'IPA', '5.80'),
('Pracownia Piwa Hadra', 'IPA', '5.90'),
('Pracownia Piwa Hazy Side of Li', 'IPA', '6.00'),
('Pracownia Piwa Honey Im Home', 'IPA', '6.90'),
('Pracownia Piwa Kwaœne Przygody', 'Fruit Beer', '4.40'),
('Pracownia Piwa LAB 25', 'Saison', '6.80'),
('Pracownia Piwa Sady Modlniczki', 'Fruit Beer', '6.00'),
('Pracownia Piwa Smoke In The So', 'Grodziskie/Gose/Lichtenhainer', '3.50'),
('Pracownia Piwa Smoki i Jednoro', 'Fruit Beer', '3.50'),
('Pracownia Piwa Sour Trip: Swed', 'Sour / Wild Ale', '5.30'),
('Pracownia Piwa Szkieletor', 'Porter - Baltic', '7.90'),
('Pracownia Piwa Tango z Mango', 'Fruit Beer', '6.70'),
('Pracownia Piwa The Deer Hunter', 'IPA - Imperial / Double', '7.50'),
('Pracownia Piwa Troszku NEIPA', 'IPA - Hazy / New England', '5.80'),
('Pracownia Piwa Wawelove', 'Pale Ale - American', '2.50'),
('Pracownia Piwa Wawelowe Porzec', 'Fruit Beer', '2.50'),
('Prairie Birthday Bomb!', 'Stout - Imperial', '13.00'),
('Prairie Bomb! Deconstructed: C', 'Stout - Imperial', '11.80'),
('Prairie Bourbon Paradise', 'Stout - Imperial', '15.90'),
('Prairie No Chill', 'Stout - Sweet', '5.10'),
('Prairie Pirate Bomb!', 'Stout - Imperial', '15.00'),
('Pressure Drop Cast Iron Billy', 'Stout - Imperial', '10.50'),
('Primátor Nealko', 'Low Alcohol', '0.50'),
('Probus Dryton/Grunwald', 'Stout - Dry', '4.50'),
('Profesja Bard', 'Pale Ale - American', '5.90'),
('Profesja Matador', 'Stout - Sweet', '6.50'),
('Profesja Pirat Porto Barrel Ag', 'Porter - Baltic', '11.50'),
('Przystanek Tlen Farmhouse Ale', 'Saison', '4.90'),
('Przystanek Tleñ Porter Tequila', 'Porter - Baltic', '10.00'),
('Przystanek Tleñ Sour Cherry Wi', 'Sour / Wild Ale', '6.00'),
('Przystanek Tleñ Sour Passionfr', 'Sour / Wild Ale', '6.00'),
('Przystanek Tlen Summer Ale z h', 'Pale Ale - American', '5.20'),
('Przystanek Tlen Vermont IPA', 'IPA - Hazy / New England', '6.00'),
('Pühaste Dekadents', 'Stout - Imperial', '11.20'),
('Raduga African Queen', 'Pale Ale - American', '5.00'),
('Raduga Apartment', 'IPA', '6.00'),
('Raduga Nosferatu', 'IPA - Black / Dark', '5.70'),
('Raduga Samurai Rebellion', 'IPA', '5.70'),
('ReCraft Quadrupel', 'Abbey Quadrupel / Abt', '9.50'),
('ReCraft Strong Ale', 'Belgian Strong Ale', '10.00'),
('ReCraft Wee Heavy', 'Scotch Ale / Wee Heavy', '8.50'),
('Revolta Tropical Wheat', 'Wheat Ale', '4.80'),
('Ritterguts Bärentöter - German', 'Grodziskie/Gose/Lichtenhainer', '6.60'),
('Rochefort Trappistes 8', 'Belgian Strong Ale', '9.20'),
('Rockmill 100m', 'IPA - Imperial / Double', '7.80'),
('Rockmill Almond Coffeecat', 'Stout - Sweet', '6.50'),
('Rockmill Black Noble', 'Stout - Imperial', '11.00'),
('Rockmill Chemistry', 'Saison', '5.50'),
('Rockmill Desmotis', 'Stout - Imperial', '12.00'),
('Rockmill Episode 10: Rauchbock', 'Smoked', '6.50'),
('Rockmill Episode 11: Calamansi', 'IPA - Hazy / New England', '5.50'),
('Rockmill Episode 9: American L', 'India Style Lager', '5.20'),
('Rockmill Get Low', 'Grodziskie/Gose/Lichtenhainer', '4.70'),
('Rockmill Going Dark Jack Danie', 'Stout - Imperial', '10.00'),
('Rockmill I had a dream', 'IPA - Hazy / New England', '6.40'),
('Rockmill Illusion', 'Stout - Imperial', '12.00'),
('Rockmill Juicy Delight', 'IPA - Hazy / New England', '6.50'),
('Rockmill Juicy Melody', 'IPA - Imperial / Double', '7.80'),
('Rockmill Ministry of Juicy', 'IPA - Session', '4.70'),
('Rockmill Mystery', 'IPA - Black / Dark', '7.00'),
('Rockmill Passion Parade', 'Berliner Weisse', '3.80'),
('Rodenbach Alexander', 'Sour Red / Brown', '6.00'),
('Rodenbach Grand Cru', 'Sour Red / Brown', '6.00'),
('Roman Ale', 'Belgian Ale', '5.00'),
('Rudy Kot', 'Imperial Pils/Strong Pale Lage', '7.00'),
('Rzeka Piwa Belzebóbr', 'Stout - Sweet', '5.80'),
('Rzeka Piwa Bobromir ', 'Pale Ale - American', '7.00'),
('Rzeka Piwa Castor de Cafe', 'Stout', '6.20'),
('Rzeka Piwa Grim Beaver', 'Wheat Ale', '4.80'),
('Rzeka Piwa Prabóbr', 'IPA - Black / Dark', '10.50'),
('Saalfelder Jubiläums Bier', 'Oktoberfest / Märzen', '5.60'),
('Saku Alkoholivaba Olu', 'Low Alcohol', '0.30'),
('Salamander Blackcurrant Milksh', 'IPA - Hazy / New England', '5.90'),
('Salamander Brut IPA', 'IPA', '6.30'),
('Salamander Chocolate Mint Fore', 'Stout - Foreign / Extra', '6.00'),
('Salamander Oatmeal Chocolate M', 'Stout - Sweet', '5.70'),
('Salamander Raspberry and Basil', 'Saison', '5.20'),
('Schneider Aventinus Weizen-Eis', 'Bock - Eisbock', '12.00'),
('Schneider Weisse Tap 5 Meine H', 'Bock - Weizenbock', '8.20'),
('Setka Apollo 19', 'Porter', '7.80'),
('Setka Sekwoja', 'IPA', '6.60'),
('Siren / Basqueland Hawaiian Sh', 'IPA', '6.40'),
('Siren / Finback Low Side', 'IPA - Hazy / New England', '6.80'),
('Siren / Slim Pickens Accept Al', 'Stout - Imperial', '9.30'),
('Siren / Superstition Mind On M', 'Stout - Imperial', '10.20'),
('Siren Lucky DIPA', 'IPA - Imperial / Double', '8.50'),
('Siren Project Barista - Breakf', 'Stout - Imperial', '9.50'),
('Solipiwko Baltic Abyss', 'Porter - Baltic', '10.30'),
('Solipiwko Barrel Nygus', 'Stout - Sweet', '7.40'),
('Solipiwko Double Nygus', 'Stout - Sweet', '7.40'),
('Solipiwko Jason', 'Pale Ale - American', '4.60'),
('Solo / Wuhan No.18 M??o???o? T', 'IPA', '6.50'),
('Sori Anniversary Barley Wine 2', 'Barley Wine / Wheat Wine', '11.60'),
('Sori Conca dOro', 'Stout - Imperial', '11.50'),
('Sori Dark Humor Club', 'Stout - Imperial', '8.00'),
('Sori Dark Humor Club Coconut', 'Stout - Imperial', '8.00'),
('Sori Dark Humor Club Heaven Hi', 'Stout - Imperial', '10.50'),
('Sori Dark Humor Club Hot Choco', 'Stout - Imperial', '10.20'),
('Sori Dark Humor Club PX Sherry', 'Stout - Imperial', '10.00'),
('Sori Ensemble Two: DDH Mosaic ', 'IPA - Imperial / Double', '8.00'),
('Sori Laudatur XVIII', 'American Strong Ale ', '10.10'),
('Sori Maximón', 'Porter - Baltic', '10.50'),
('Sori Pareto 2017 (Port Wine Ba', 'Scotch Ale / Wee Heavy', '11.50'),
('Spiz AIPA', 'IPA', '0.00'),
('Spiz Ciemne (Dunkelbier) 13 %', 'Dunkel / Tmavy', '6.00'),
('Spiz Czekoladowe', 'Spice / Herb / Vegetable', '6.00'),
('Spiz Jasne', 'Premium Lager', '0.00'),
('Spiz Miodowe', 'Spice / Herb / Vegetable', '0.00'),
('Spiz Pils', 'Pilsener', '0.00'),
('Spiz Pszeniczne (Weizenbier)', 'Weissbier - Hefeweizen', '3.50'),
('Spó³dzielczy / Piwoteka Ro¿kow', 'Grodziskie/Gose/Lichtenhainer', '3.50'),
('Spó³dzielczy Gordyjyskie', 'Abbey Tripel', '8.20'),
('Spó³dzielczy Knagowe', 'IPA', '6.20'),
('Spó³dzielczy Proste', 'Pilsener', '5.00'),
('Spó³dzielczy Rozwojowe', 'Pale Ale - American', '5.00'),
('Spó³dzielczy Wyblinkowe', 'Sour / Wild Ale', '3.50'),
('St-Feuillien Triple', 'Abbey Tripel', '8.50'),
('St. Bernardus Abt 12', 'Abbey Quadrupel / Abt', '10.00'),
('Stara Zajezdnia Œliwkowe (Plum', 'Fruit Beer', '4.80'),
('Staropolski Cfany ZBEER', 'Premium Lager', '4.20'),
('Staropolski Karaibski BEERat ', 'Wheat Ale', '4.80'),
('Staropolski Kultowe Karmelowe', 'Dunkel / Tmavy', '4.80'),
('Staropolski Staropolskie Miodn', 'Spice / Herb / Vegetable', '4.70'),
('Staropolski Whisky Stout', 'Smoked', '6.20'),
('Staropramen Ležák (Premium Lag', 'Czech Pilsner (Svìtlý)', '5.00'),
('Stary Browar Koœcierzyna Irish', 'Irish Ale', '4.50'),
('Struise Black Damnation XIX - ', 'Stout - Imperial', '13.00'),
('Struise Black Damnation XVIII ', 'Stout - Imperial', '13.00'),
('Struise Pannepot (10%)', 'Belgian Strong Ale', '10.00'),
('Struise Randolique', 'Abbey Tripel', '8.00'),
('Struise Zombination II (L.E.M.', 'Stout - Imperial', '17.00'),
('Struise Zombination V (M.A.N.O', 'Stout - Imperial', '17.00'),
('Svijanská Knìžna 13°', 'Dunkel / Tmavy', '5.20'),
('Sza³piw Fest Buba', 'Abbey Quadrupel / Abt', '11.00'),
('Sza³piw Rubus Idaeus Maleficus', 'Sour / Wild Ale', '6.60'),
('Szpunt / Doctor Brew Astronom', 'IPA - Imperial / Double', '10.00'),
('Szpunt / Golem StoIBU', 'IPA - Hazy / New England', '6.00'),
('Szpunt / Golem ZeroIBU', 'IPA - Hazy / New England', '6.00'),
('Szpunt Nigami', 'IPA', '5.90'),
('Szpunt Tianajpa', 'IPA', '6.00'),
('Szpunt Wormhole Bourbon BA', 'IPA - Imperial / Double', '8.00'),
('T.E.A Time Black Prince', 'Porter', '5.00'),
('T.E.A Time Cherokee', 'Wheat Ale', '4.50'),
('T.E.A Time Nettletrasher', 'Premium Bitter / ESB', '4.80'),
('T.E.A Time Platinum Blonde', 'Golden Ale / Blond Ale', '4.00'),
('T.E.A Time Podgorskie', 'Pale Ale - English', '4.00'),
('T.E.A Time Smooth Hopperator', 'Amber Ale', '4.20'),
('T.E.A Time Triumph', 'IPA - Session', '4.50'),
('T.E.A Time White Wolf', 'Stout', '6.00'),
('Tattooed Beer Foxy Lady', 'Specialty Grain', '0.00'),
('Tattooed Beer Rosemary', 'Sour / Wild Ale', '0.00'),
('Tattooed Beer Sailor Girl', 'IPA', '6.20'),
('Tattooed Beer Suzie Q', 'Pale Ale - American', '5.20'),
('Tempest All The Leaves Are Bro', 'Brown Ale', '11.20'),
('Tempest Brave New World IPA', 'IPA', '7.00'),
('Tempest Dawsons Kviek', 'IPA', '5.30'),
('Tempest Red Eye Flight', 'Porter', '7.40'),
('Tempest Trimontium ', 'IPA - Hazy / New England', '6.50'),
('Tenczynek Bock', 'Bock - Dunkler / Urbock', '6.80'),
('Tenczynek P American Wheat', 'Wheat Ale', '4.50'),
('Tenczynek P IPA', 'IPA', '6.00'),
('Tenczynek P Milk Stout', 'Stout - Sweet', '4.80'),
('Tenczynek Pils', 'Pilsener', '5.40'),
('Tesco Finest Porter', 'Porter', '5.30'),
('Tesco Finest Unfiltered Wheat ', 'Fruit Beer', '4.20'),
('The Bruery Poterie', 'Old Ale', '16.80'),
('The Garage Monks Dudette', 'IPA', '7.00'),
('The Garage Monks Hop Trigger', 'Pale Ale - American', '4.80'),
('The Garage Monks Redneck', 'Berliner Weisse', '4.30'),
('The Garage Monks Wiseguy', 'IPA', '6.50'),
('The Hop Concept Hop Freshener ', 'IPA - Imperial / Double', '8.00'),
('The Kernel Biere de Saison - D', 'Saison', '4.40'),
('The Kernel Dry Stout Mandarina', 'Stout', '4.50'),
('The Kernel Dry Stout Simcoe', 'Stout - Dry', '4.30'),
('The Kernel Imperial Brown Stou', 'Stout - Imperial', '10.10'),
('The Kernel India Pale Ale Cent', 'IPA', '7.30'),
('The Kernel India Pale Ale Citr', 'IPA', '7.10'),
('Thornbridge Fika', 'Stout', '7.40'),
('Three Floyds / Mikkeller Hvede', 'Barley Wine / Wheat Wine', '10.40'),
('Tiny Rebel / Fierce Beer Orang', 'Stout', '7.00'),
('Tiny Rebel Clwb Tropicana', 'IPA', '5.50'),
('Tiny Rebel Hadouken', 'IPA', '7.40'),
('Tiny Rebel Imperial Puft', 'Porter - Imperial / Double', '9.00'),
('Tiny Rebel Stay Puft Imperial ', 'Porter - Imperial / Double', '9.00'),
('Tiny Rebel The Great Cornholio', 'IPA - Imperial / Double', '8.40'),
('To Ol Black Bauble (Santa Top ', 'Spice / Herb / Vegetable', '8.00'),
('To Ol Campale', 'Golden Ale / Blond Ale', '6.00'),
('To Ol Goliat Imperial Coffee S', 'Stout - Imperial', '10.10'),
('To Ol Gose To Hollywood', 'Grodziskie/Gose/Lichtenhainer', '3.80'),
('To Ol Sur Tangerine/Mosaic Lem', 'Radler / Shandy', '2.80'),
('Toccalmatto Maciste Heroic Dou', 'IPA - Imperial / Double', '8.50'),
('Toccalmatto Re Hop', 'Pale Ale - American', '5.00'),
('Toppling Goliath Pseudo Sue', 'Pale Ale - American', '6.80'),
('Toppling Goliath Tsunami Pale ', 'Pale Ale - American', '5.00'),
('Trzech Kumpli / Piwne Podziemi', 'Abbey Tripel', '8.60'),
('Trzech Kumpli American Beauty', 'Golden Ale / Blond Ale', '5.00'),
('Trzech Kumpli Blackcyl', 'IPA - Black / Dark', '7.00')
('Trzech Kumpli Blackcyl Special', 'IPA - Black / Dark', '7.00'),
('Trzech Kumpli Brew Note', 'IPA - Black / Dark', '4.50'),
('Trzech Kumpli Califia', 'IPA', '7.00'),
('Trzech Kumpli Feelin Lucky', 'IPA', '6.10'),
('Trzech Kumpli Goedemorgen', 'IPA', '6.50'),
('Trzech Kumpli Happy Days', 'Low Alcohol', '1.30'),
('Trzech Kumpli Idiota', 'Stout - Imperial', '10.50'),
('Trzech Kumpli Misty', 'IPA - Hazy / New England', '5.50'),
('Trzech Kumpli MVPils', 'India Style Lager', '4.40'),
('Trzech Kumpli Otwarcie Sezonu', 'Saison', '5.70'),
('Trzech Kumpli PIA', 'IPA - Session', '4.40'),
('Trzech Kumpli Piece of Cake', 'IPA', '5.80'),
('Trzech Kumpli Pils', 'Pilsener', '4.40'),
('Trzech Kumpli Piwo w Stylu Gro', 'Grodziskie/Gose/Lichtenhainer', '2.90'),
('Trzech Kumpli Ragnar', 'Porter - Baltic', '11.00'),
('Trzech Kumpli Szczyt Sezonu', 'Saison', '7.40'),
('Trzech Kumpli Taura', 'IPA - Imperial / Double', '6.60'),
('Trzech Kumpli Weizen', 'Weissbier - Hefeweizen', '5.00'),
('Trzy Korony Gazda', 'Oktoberfest / Märzen', '6.00'),
('Trzy Korony Nowy Sacz Dunkel', 'Dunkel / Tmavy', '5.00'),
('Trzy Korony Nowy Sacz KoŸlak', 'Bock - Dunkler / Urbock', '7.50'),
('Tyskie Gronie', 'Pale Lager', '5.50'),
('Uiltje Amarillo Armadillo', 'IPA - Imperial / Double', '9.40'),
('Uiltje Mosaic Mammoth', 'IPA - Imperial / Double', '8.00'),
('Uiltje Schwarzwälderkirsch Che', 'Stout - Imperial', '8.00'),
('Ursa Maior Drapie¿nik', 'IPA - Session', '5.00'),
('Ursa Maior Dwa Misie', 'Belgian Strong Ale', '6.70'),
('Ursa Maior Dziki Kot z Berehów', 'IPA', '6.00'),
('Ursa Maior Sen Bieszczadnika', 'IPA', '6.00'),
('Ursa Maior Œnieg na Beniowej', 'Golden Ale / Blond Ale', '4.20'),
('Ursa Maior Wataha', 'English Strong Ale', '7.20'),
('Verhaeghe Duchesse De Bourgogn', 'Sour Red / Brown', '6.20'),
('Verhaeghe Echt Kriekenbier', 'Sour / Wild Ale', '6.80'),
('Verzet Kameradski Balsamico', 'Sour / Wild Ale', '13.50'),
('Victory Art Brew / Brokreacja ', 'Grodziskie/Gose/Lichtenhainer', '6.30'),
('Vocation Love & Hate 7.2%', 'IPA - Hazy / New England', '7.20'),
('Volfas Engelman Blond', 'Witbier', '4.50'),
('W¹sosz 15 ', 'Imperial Pils/Strong Pale Lage', '7.80'),
('W¹sosz Opowieœæ Wigilijna', 'Spice / Herb / Vegetable', '6.40'),
('W¹sosz Piwo Bo¿onarodzeniowe', 'Spice / Herb / Vegetable', '9.00'),
('Waszczukowe American Pils', 'India Style Lager', '4.70'),
('Waszczukowe Desitka', 'Czech Pilsner (Svìtlý)', '4.10'),
('Waszczukowe Dry Stout', 'Stout - Dry', '5.30'),
('Waszczukowe Porter z Puszczy', 'Porter - Baltic', '10.00'),
('Wawelskie Pils 11%', 'Pilsener', '4.20'),
('Wawelskie Pszeniczne', 'Weissbier - Hefeweizen', '5.50'),
('Weird Beard / Northern Monk Ha', 'Barley Wine / Wheat Wine', '11.60'),
('Weird Beard Black Perle 3.8 %', 'Stout - Sweet', '3.80'),
('Weird Beard Decadence', 'Stout', '5.50'),
('Weird Beard Fade to Black', 'IPA - Black / Dark', '6.30'),
('Weird Beard Five OClock Shado', 'IPA', '7.30'),
('Weird Beard Hasbean Heavy Fuel', 'Smoked', '5.30'),
('Weird Beard Holy Hoppin Hell (', 'IPA - Imperial / Double', '9.50'),
('Weird Beard Sour Slave - Mosai', 'Sour / Wild Ale', '4.00'),
('Westbrook 7th Anniversary Choc', 'Stout - Imperial', '10.00'),
('Weyerbacher Tiny', 'Stout - Imperial', '11.80'),
('Wicked Weed Old Fashioned', 'Old Ale', '10.00'),
('Widawa Fruit Bomb! IPA', 'IPA', '6.20'),
('Widawa Hazy Hazi', 'IPA - Hazy / New England', '6.20'),
('Widawa Pogromca', 'Barley Wine / Wheat Wine', '11.00'),
('Widawa Porter Ba³tycki Wêdzony', 'Porter - Baltic', '10.50'),
('Widawa Simcoe Pils', 'Pilsener', '4.70'),
('Wild Beer / Hanging Bat / Blac', 'Belgian Strong Ale', '13.00'),
('Wild Beer / Side Project Rosa ', 'Saison', '5.00'),
('Wild Beer Beyond Modus IV', 'Sour Red / Brown', '8.00'),
('Wild Beer Bruty & the Yeast', 'IPA', '6.60'),
('Wild Beer Evolver IPA', 'IPA', '5.80'),
('Wild Beer Nebula', 'IPA - Session', '5.00'),
('Wild Beer Rooting Around - Aut', 'Sour / Wild Ale', '4.60'),
('Wild Beer Rooting Around - Sum', 'Sour / Wild Ale', '6.00'),
('Wild Beer Sleeping Lemons', 'Grodziskie/Gose/Lichtenhainer', '3.60'),
('Wild Beer Smoke Barrels Is', 'Smoked', '7.40'),
('Wild Beer Wildebeest', 'Stout - Imperial', '11.00'),
('Wild Beer Zintuki', 'Sour / Wild Ale', '7.30'),
('Witnica Lubuskie Czeska Dziesi', 'Czech Pilsner (Svìtlý)', '4.20'),
('Wizyta Gospodarska', 'Porter', '8.10'),
('WRCLW Barley Wine', 'Barley Wine / Wheat Wine', '9.60'),
('WRCLW Barley Wine Nitro Rum BA', 'Barley Wine / Wheat Wine', '10.60'),
('WRCLW Imperial Stout Nitro Bou', 'Stout - Imperial', '11.00'),
('WRCLW Pils', 'Pilsener', '5.00'),
('WRCLW Rye RIS Porto & Bourbon ', 'Stout - Imperial', '10.20'),
('Wrê¿el ABRA', 'Specialty Grain', '5.60'),
('Wrê¿el AIPA', 'IPA', '6.80'),
('Wrê¿el Grejpfrut IPA', 'IPA', '6.30'),
('Wrê¿el Tropical Black IIPA', 'IPA - Black / Dark', '8.50'),
('Yeastie Boys Pot Kettle Black', 'IPA - Black / Dark', '6.00'),
('Za Miastem Cicha Noc', 'Stout - Sweet', '5.60'),
('Za Miastem Cichy Wieczór', 'Specialty Grain', '5.80'),
('Za Miastem Œwiêty Spokój', 'IPA', '6.50'),
('Zakarpatske Originalne', 'Pale Lager', '4.00'),
('Zak³adowy 300% Normy', 'IPA - Imperial / Double', '8.40'),
('Zak³adowy 400% normy ', 'IPA - Imperial / Double', '8.10'),
('Zak³adowy Ciê¿ki £adunek', 'IPA - Imperial / Double', '8.10'),
('Zak³adowy Dzia³ Testowy #1', 'Bock - Weizenbock', '7.40'),
('Zak³adowy Dzia³ Testowy #2', 'Abbey Quadrupel / Abt', '9.20'),
('Zak³adowy Koktajl Towarzyski', 'IPA - Session', '4.00'),
('Zak³adowy Kontenerowiec', 'Pale Ale - American', '4.00'),
('Zak³adowy Mleczarz', 'Stout - Sweet', '5.50'),
('Zak³adowy Pan Portier', 'Porter - Baltic', '9.70'),
('Zak³adowy Podwójny Wniosek Url', 'IPA - Imperial / Double', '8.40'),
('Zak³adowy Produkt Wzorcowy', 'IPA', '6.30'),
('Zak³adowy Wniosek Urlopowy', 'IPA', '6.60'),
('Zak³adowy Wyp³ata', 'IPA - Hazy / New England', '5.30'),
('Zak³adowy Zaprawa', 'Helles', '5.30'),
('Zambos Beer Special', 'Pale Lager', '3.00'),
('Zamkowy Cieszyn / PiwoWarownia', 'Spice / Herb / Vegetable', '5.50'),
('Zamkowy Cieszyn Cieszyñski KoŸ', 'Bock - Doppelbock', '8.90'),
('Zamkowy Cieszyn Noszak', 'Pale Lager', '5.00'),
('Zamkowy Cieszyn Rye Wine Ciesz', 'Barley Wine / Wheat Wine', '9.90'),
('Žatec Plavèík', 'Czech Pilsner (Svìtlý)', '3.80'),
('Ziemia Obiecana Hallo Berlin!', 'IPA - Session', '5.50'),
('Ziemia Obiecana Luis', 'Saison', '5.60'),
('Ziemia Obiecana Nudna Belgia', 'IPA', '6.00'),
('Ziemia Obiecana Sydnej', 'IPA', '5.80'),
('Ziemia Obiecana Tak Trzeba ¯yæ', 'Sour / Wild Ale', '5.70'),
('Zubr Classic Tmavé', 'Dunkel / Tmavy', '4.10'),
('¯ywiec Sesyjne IPA', 'IPA - Session', '5.00'),
('Z³oty £an APA', 'Pale Ale - American', '5.50'),
('£añcut / Pinta Kryszta³', 'Pale Lager', '5.20'),
('£añcut Czarna Polewka', 'Stout', '4.80'),
('£añcut Czarny Piotruœ', 'IPA - Black / Dark', '5.50'),
('£añcut Das Is Kwass', 'Berliner Weisse', '3.40'),
('£añcut Das Is Kwass Wiœnia Mal', 'Berliner Weisse', '3.40'),
('£añcut Flanders Brett', 'Sour / Wild Ale', '6.70'),
('£añcut Flanders Roselare ', 'Sour Red / Brown', '6.70'),
('£añcut Pospolite Ruszenie', 'Pale Ale - American', '5.10'),
('£añcut Rajsky Plyn', 'Czech Pilsner (Svìtlý)', '5.00'),
('£añcut Ry¿a IPA', 'IPA', '6.40'),
('£añcut Trapper', 'IPA', '5.20'),
('£añcut Zawisza Czarny', 'Stout - Imperial', '9.50');
COMMIT;